# Travis CI configuration
language: php
php:
  - '7.0'
  - '7.1'
before_install:
  - echo "soap.wsdl_cache_enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "soap.wsdl_cache_limit = 10" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
install: travis_retry composer install --no-interaction --prefer-dist --no-suggest
script: vendor/bin/phpunit